In [1]:
import cv2
import numpy as np

# Create point matrix get coordinates of mouse click on image
point_matrix = np.array([[0,0],[0,0],[0,0],[0,0]],int)
dst = np.array([[0,0],[0,450],[600,450],[600,0]],np.float32) 
    
counter = 0
def mousePoints(event,x,y,flags,params):
    global counter
    if event == cv2.EVENT_LBUTTONDOWN and counter < 4:
        point_matrix[counter] = x,y
        counter = counter + 1
        
def find_homography(source,destin):

    A = []
    for src,dst in zip(source,destin):
        p1 = np.matrix([src[0],src[1],1])
        p2 = np.matrix([dst[0],dst[1],1])              
        a1 = [-src[0], -src[1], -1, 0, 0, 0, dst[0] * src[0], dst[0] * src[1], dst[0]]    
        a2 = [0, 0, 0, -src[0], -src[1], -1, dst[1] * src[0], dst[1] * src[1], dst[1]]     
        A.append(a1)
        A.append(a2)
      
    a , b, v = np.linalg.svd(np.matrix(A))
    h = np.reshape(v[8], (3, 3))
    return h

In [ ]:
# Read image
img = cv2.imread("3.jpeg")
 
while True:
    for x in range (0,4):
        cv2.circle(img,(point_matrix[x][0],point_matrix[x][1]),3,(0,255,0),cv2.FILLED)

    cv2.imshow("Original Image ", img)
    cv2.setMouseCallback("Original Image ", mousePoints)
    cv2.waitKey(1)
    
    if counter == 4:
        print("Calculating.")
        cv2.waitKey(1)
        
        mat = cv2.getPerspectiveTransform(point_matrix.astype(np.float32),dst)
        print(f"This is opencv = {mat}\n ******************")
        
        matComputed = find_homography(point_matrix,dst)
        print(f"This is me = {matComputed}\n ******************")
        
        resultimageOPENCV = cv2.warpPerspective(img, np.array(mat),(600,450))
        resultimageCOMPUTED = cv2.warpPerspective(img, np.array(matComputed),(600,450))
        while True:
            cv2.imshow("opencv homography",resultimageOPENCV)
            cv2.imshow("computed homography",resultimageCOMPUTED)
            cv2.waitKey(1)
        break;

Calculating.
This is opencv = [[ 9.36382171e-01  8.21902846e-02 -2.06409158e+02]
 [-3.50737150e-01  1.16181681e+00 -1.73132626e+02]
 [-6.67051291e-04 -7.27984932e-05  1.00000000e+00]]
 ******************
This is me = [[-3.47564706e-03 -3.05072469e-04  7.66145925e-01]
 [ 1.30186006e-03 -4.31241144e-03  6.42630671e-01]
 [ 2.47594939e-06  2.70212182e-07 -3.71178262e-03]]
 ******************
